name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: install java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: '17'
    - name: install clojure
      uses: DeLaGuardo/setup-clojure@13.2
      with:
        cli: 1.12.2.1565
    - name: test
      run: clojure -X:test
