name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - {name: install, run: lein deps}
    - name: test
      run: lein test
    # Deploy manually for a time
    # - name: deploy
    #   env:
    #     CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
    #     CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
    #   run: lein deploy clojars
    #   if: github.ref == 'master'
